### ISSUE TITLE
Make CRUD for crimes

### ISSUE THREAD

**Issue by yashodgayashan** [Reforest-Sri-Lanka/nep#28]

**Comment by Sharukap** [comment]
Is this to do the crud operations on crime types table so that they won't be hardcoded anymore? @yashodgayashan

**Comment by yashodgayashan** [comment]
@AselGunaratne

**Comment by AselGunaratne** [comment]
Crud operations for crime types have been completed and pull request been made (Crime types can be viewed,added, edited an deleted by the admin/super admin and hardcoded values has been removed from log complaint instead crime types fetched from table
